package storage

import (
	"time"

	"github.com/google/uuid"
)

type ScreenshotRecord struct {
	ID        string    `db:"id"`
	Timestamp time.Time `db:"timestamp"`
	ScreenID  int       `db:"screen_id"`
	ImagePath string    `db:"image_path"`
	// Summary contains factual description of what the user is doing in the screenshot
	// This is generated by analyzing the screenshot image
	Analysis string `db:"analysis"` // Keep field name for DB compatibility, but semantically it's a summary
	HourKey  string `db:"hour_key"`
}

type HourSummary struct {
	HourKey     string    `db:"hour_key"`
	Date        time.Time `db:"date"`
	Hour        int       `db:"hour"`
	Screenshots string    `db:"screenshots"`
	Summary     string    `db:"summary"`
}

type PeriodSummary struct {
	PeriodKey   string    `db:"period_key"`
	PeriodType  string    `db:"period_type"`
	StartTime   time.Time `db:"start_time"`
	EndTime     time.Time `db:"end_time"`
	Screenshots string    `db:"screenshots"`
	// Summary contains factual information extracted from screenshots
	// It is a consolidation of what happened during this period
	Summary string `db:"summary"`
	// Analysis contains improvement suggestions and behavioral insights
	// It is generated based on the summary content
	Analysis string `db:"analysis"`
}

func (r *ScreenshotRecord) GenerateHourKey() {
	t := r.Timestamp
	r.HourKey = t.Format("2006-01-02-15")
}

func NewScreenshotRecord(screenID int, imagePath string) *ScreenshotRecord {
	now := time.Now()
	record := &ScreenshotRecord{
		ID:        generateID(),
		Timestamp: now,
		ScreenID:  screenID,
		ImagePath: imagePath,
	}
	record.GenerateHourKey()
	return record
}

func generateID() string {
	return uuid.New().String()
}

// RollingCheckpoint 滚动汇总检查点
type RollingCheckpoint struct {
	ID                  string    `db:"id"`
	SessionID           string    `db:"session_id"`
	PeriodKey           string    `db:"period_key"`
	CurrentStep         int       `db:"current_step"`
	TotalSteps          int       `db:"total_steps"`
	ProcessedItems      string    `db:"processed_items"`
	IntermediateSummary string    `db:"intermediate_summary"`
	CreatedAt           time.Time `db:"created_at"`
}
